services:
  neo4j:
    image: neo4j:${NEO4J_VERSION}
    container_name: graph_db
    ports:
      - 7474:7474 # GUI
      - 7687:7687 # Web API
    expose:
      - 7474
      - 7687
    volumes:
      - ./.docker/neo4j/data:/data
      - ./.docker/neo4j/logs:/logs
      - ./.docker/neo4j/conf:/conf
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/passwordneo # user/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
