[tool.poetry]
name = "knowde"
version = "0.0.0" # poetry-dynamic-versioningでgit tagの値にに置換される
description = ""
authors = ["Shogo Goto <gotoadmn0605@gmail.com>"]
readme = "README.md"
repository = "https://github/com/shogogoto/knowde"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
typer = {extras = ["all"], version = "^0.9.0"}
neomodel = "^5.2.0"
uvicorn = "^0.24.0.post1"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.0"
pytest = "^7.4.3"
pre-commit = "^3.5.0"
requests-mock = "^1.11.0"
pytest-watch = "^4.2.0"
ruff = "^0.1.5"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.taskipy.tasks]
test       = "pytest -s -v"
test-watch = "pytest-watch -- -v -s --durations=0 --ff"
lint       = "ruff check ."
lintfix    = "ruff . --fix"
pre-commit = "pre-commit install"

[tool.ruff]
select = ["ALL"]
ignore = [
  "ERA001", # found commented-out code
]

# ref: https://github.com/scikit-build/scikit-build/issues/951#issuecomment-1645302094
[tool.pytest.ini_options]
filterwarnings = [
  'ignore: pkg_resources is deprecated as an API:DeprecationWarning',
]

