// 入力するテキストファイルの文法定義
?start: _NL? (s1|s2|s3|s4|s5|s6)*
s: s1
  |s2
  |s3
  |s4
  |s5
  |s6

_W: /.+/
_EOF: "$"

H1: /(#[^#\n]+)/
H2: /(##[^#\n]+)/
H3: /(###[^#\n]+)/
H4: /(####[^#\n]+)/
H5: /(#####[^#\n]+)/
H6: /(######[^#\n]+)/

COMMENT: /\![^\n]+/

s1: H1 (COMMENT)* (s2)*
s2: H2 (COMMENT)* (s3)*
s3: H3 (COMMENT)* (s4)*
s4: H4 (COMMENT)* (s5)*
s5: H5 (COMMENT)* (s6)*
s6: H6 (COMMENT)*

%import common.WS
%import common.NEWLINE -> _NL
%import common.ESCAPED_STRING
%ignore WS
