name: Upload Standalone Asset

on:
  release:
    types:
      - created
      - edited
      - prereleased
      - published
  push:
    tags:
      - 'v*'

jobs:
  standalone:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning twine
      - name: Create standalone
        run: |
          poetry install
          poetry run task build
          # echo "VARS::: " ${{ github.ref_name }} ${{ github.event.release.tag_name }}
          # mkdir standalone
          zip -r standalone.zip standalone
      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: standalone.zip
          tag_name: ${{ github.event.release.tag_name }}
          draft: true
          prerelease: true
