name: Upload Standalone Asset

on:
  release:
    types: [created]

jobs:
  standalone:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning twine
      - name: Create standalone executable file
        run: |
          poetry install
          poetry run task build
          zip -r standalone.zip standalone
      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/standalone.zip
            tag_name: ${{ env.RELEASE_TAG }}
            name: ${{ env.RELEASE_TAG }}
            draft: true
            prerelease: true
