name: Upload Standalone Asset

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  standalone:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: python -m pip install --upgrade pip
      - run: poetry install --without dev

      - name: Install dependencies
        run: |
          pip install poetry-dynamic-versioning twine
      - name: Create standalone
        run: |
          poetry dynamic-versioning
          poetry run task build
      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: standalone/dist/kn
          tag_name: ${{ github.event.release.tag_name }}
          draft: true
          prerelease: true

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning twine
          poetry install --without dev
      - name: Create standalone
        run: |
          poetry dynamic-versioning
          poetry run task build
          # Compress-Archive -Path standalone  -DestinationPath win.zip
      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: standalone/dist/kn.exe
          tag_name: ${{ github.event.release.tag_name }}
          draft: true
          prerelease: true
